apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokeclone-backend
  labels:
    app: pokeclone-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokeclone-backend
  template:
    metadata:
      labels:
        app: pokeclone-backend
    spec:
      containers:
        - name: pokeclone-backend
          image: jeremyhuegel/pokeclone_backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DJANGO_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: 'DJANGO_KEY'

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: POSTGRES_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DB_HOST
            - name: DB_PORT
              value: '5432'
            
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
      # volumes:
      #   - name: pokeclone-backend-volume
      #     persistentVolumeClaim:
      #       claimName: pokeclone-backend-pvc