apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  POSTGRES_USER: dGVhbXJvY2tldA==
  POSTGRES_PASSWORD: UE9LRVRlYW1Sb2NrZXQz
  POSTGRES_DB: cG9rZWNsb25lX2Ri
  DJANGO_KEY: cG9rZWNsb25l
  DB_HOST: dGVhbS1yb2NrZXQtcG9zdGdyZXMtZGIuY2RvbW9jeXdxNDNlLnVzLWVhc3QtMi5yZHMuYW1hem9uYXdzLmNvbQ==
