apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: cG9rZWNsb25lX2Ri
  DJANGO_KEY: cG9rZWNsb25l
  DB_HOST: cG9zdGdyZXMuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA==
