name: Terraform Destroy

on:
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  destroy:
    name: Destroy Terraform Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.FLO_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.FLO_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./iac

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var="FLO_DB_USERNAME=${{ secrets.FLO_DB_USERNAME }}" -var="FLO_DB_PASSWORD=${{ secrets.FLO_DB_PASSWORD }}"
        working-directory: ./iac
